import React from "react";

const Home = () => {
  return (
      <div className="home-container">
            {/* Hero Section */}
                  <section className="hero">
                          <div className="hero-overlay">
                                    <h1>GBTS Builders Solution Ltd</h1>
                                              <p className="tagline">Your One-Stop-Store for Building Materials</p>
                                                      </div>
                                                            </section>

                                                                  {/* Why Choose GBTS */}
                                                                        <section className="why-gbts">
                                                                                <h2>Why Choose GBTS?</h2>
                                                                                        <div className="reasons-grid">
                                                                                                  <div className="reason-card">
                                                                                                              <h3>24/7 Support</h3>
                                                                                                                          <p>Always available to attend to your orders and concerns.</p>
                                                                                                                                    </div>
                                                                                                                                              <div className="reason-card">
                                                                                                                                                          <h3>Quality Products</h3>
                                                                                                                                                                      <p>Only premium materials from trusted manufacturers.</p>
                                                                                                                                                                                </div>
                                                                                                                                                                                          <div className="reason-card">
                                                                                                                                                                                                      <h3>Fast Delivery</h3>
                                                                                                                                                                                                                  <p>Swift and safe delivery to your site or home.</p>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                      <div className="reason-card">
                                                                                                                                                                                                                                                  <h3>Affordable Pricing</h3>
                                                                                                                                                                                                                                                              <p>We offer competitive prices across all our categories.</p>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                            {/* Product Categories */}
                                                                                                                                                                                                                                                                                                  <section className="product-categories">
                                                                                                                                                                                                                                                                                                          <h2>Our Product Categories</h2>
                                                                                                                                                                                                                                                                                                                  <div className="categories-grid">
                                                                                                                                                                                                                                                                                                                            <div className="category-card" style={{ backgroundImage: "url('https://res.cloudinary.com/dcxga7ojb/image/upload/v1748453709/roofnw1.jpg')" }}>
                                                                                                                                                                                                                                                                                                                                        <div className="overlay">
                                                                                                                                                                                                                                                                                                                                                      <h3>Roofings</h3>
                                                                                                                                                                                                                                                                                                                                                                    <p>Durable and aesthetic roofing sheets.</p>
                                                                                                                                                                                                                                                                                                                                                                                  <a className="cta-button" href="roofings.html">Explore</a>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="category-card" style={{ backgroundImage: "url('https://res.cloudinary.com/dcxga7ojb/image/upload/v1748376893/Lock4.jpg')" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="overlay">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Locks & Knobs</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Secure your property with smart locks and knobs.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a className="cta-button" href="locks.html">Browse</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Blog Excerpts */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="blog-excerpts">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Latest from Our Blog</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="blog-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="blog-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>5 Roofing Trends in 2025</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Explore modern roofing designs making waves this year.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a className="read-more" href="blog-posts.html">Read More</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="blog-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Choosing the Right Security Lock</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Tips on selecting smart locks for your building.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a className="read-more" href="blog-posts.html">Read More</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Footer remains unchanged */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Home;