import React from "react";
import "./HomePage.css";

const HomePage = () => {
  return (
      <div>
            {/* Hero Section */}
                  <section className="hero">
                          <div className="hero-overlay">
                                    <h1>GBTS Builders Solution Ltd</h1>
                                              <p className="tagline">Your One-Stop-Store for Building Materials</p>
                                                        <a href="products.html" className="cta-button">Shop Now</a>
                                                                </div>
                                                                      </section>

                                                                            {/* Features Section */}
                                                                                  <section className="features">
                                                                                          <h2>Why Choose GBTS?</h2>
                                                                                                  <div className="feature-grid">
                                                                                                            <div className="feature-item">
                                                                                                                        <i className="fas fa-truck"></i>
                                                                                                                                    <h3>Fast Delivery</h3>
                                                                                                                                                <p>Nationwide delivery of all materials at unbeatable speed.</p>
                                                                                                                                                          </div>
                                                                                                                                                                    <div className="feature-item">
                                                                                                                                                                                <i className="fas fa-check-circle"></i>
                                                                                                                                                                                            <h3>Quality Assurance</h3>
                                                                                                                                                                                                        <p>We only sell genuine and durable building products.</p>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                            <div className="feature-item">
                                                                                                                                                                                                                                        <i className="fas fa-headset"></i>
                                                                                                                                                                                                                                                    <h3>24/7 Support</h3>
                                                                                                                                                                                                                                                                <p>Our experts are always ready to help with your inquiries.</p>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                              {/* Categories */}
                                                                                                                                                                                                                                                                                                    <section className="categories">
                                                                                                                                                                                                                                                                                                            <h2>Shop by Category</h2>
                                                                                                                                                                                                                                                                                                                    <div className="category-grid">
                                                                                                                                                                                                                                                                                                                              <div className="category-card">
                                                                                                                                                                                                                                                                                                                                          <img src="https://res.cloudinary.com/dcxga7ojb/image/upload/v1748453709/roofnw1.jpg" alt="Roofings" />
                                                                                                                                                                                                                                                                                                                                                      <h3>Roofings</h3>
                                                                                                                                                                                                                                                                                                                                                                  <a href="roofings.html" className="cta-button">Explore</a>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="category-card">
                                                                                                                                                                                                                                                                                                                                                                                                  <img src="https://res.cloudinary.com/dcxga7ojb/image/upload/v1747730406/istockphoto-596042932-612x612_1_ryfysn.jpg" alt="Hand Tools" />
                                                                                                                                                                                                                                                                                                                                                                                                              <h3>Hand Tools</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="hand-tools.html" className="cta-button">Explore</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="category-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img src="https://res.cloudinary.com/dcxga7ojb/image/upload/v1747730443/Lock3.jpg" alt="Locks" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Locks & Knobs</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="locks-knobs.html" className="cta-button">Explore</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Blog Highlights */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="blog-excerpts">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>From Our Blog</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="blog-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="blog-post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Top 5 Roofing Materials in 2025</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Explore the most durable and cost-effective options for your next building project.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="blog-posts.html" className="read-more">Read More</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="blog-post">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Why Smart Locks Are Changing Home Security</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Learn how keyless entry systems can secure your property and simplify access.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="blog-posts.html" className="read-more">Read More</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="footer-links">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="about-us.html">About Us</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="contact-us.html">Contact Us</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="return-policy.html">Return Policy</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="faq.html">FAQ</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="terms.html">Terms of Service</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="privacy-policy.html">Privacy Policy</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="blog-posts.html">Blog</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <address>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Shop 1 Jubilee Market, Ikare Akoko 342211, Ondo State, Nigeria.<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Email: <a href="mailto:ask@gbtsbuildingmaterials.com">ask@gbtsbuildingmaterials.com</a><br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Phone: <a href="tel:+2347017742003">+2347017742003</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </address>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="social-media">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="https://facebook.com/profile.php?id=61575683557550" target="_blank" rel="noreferrer"><i className="fab fa-facebook-f"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="https://x.com/gbtsstores" target="_blank" rel="noreferrer"><i className="fab fa-twitter"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="https://instagram.com/gbtsstores" target="_blank" rel="noreferrer"><i className="fab fa-instagram"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="https://pinterest.com/gbtsstores" target="_blank" rel="noreferrer"><i className="fab fa-pinterest"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="https://wa.me/7017742003" target="_blank" rel="noreferrer"><i className="fab fa-whatsapp"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="copyright">© 2025 GBTS Builders Solution Ltd.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default HomePage;