import React from "react";
import "./HomePage.css";

const HomePage = () => {
  return (
      <div className="homepage">
            {/* Hero Section */}
                  <section className="hero">
                          <div className="hero-content">
                                    <h1>GBTS Builders Solution Ltd</h1>
                                              <p className="tagline">Your One-Stop-Store for Building Materials</p>
                                                        <Link to="/products" className="cta-button">Shop Now</Link>
                                                                </div>
                                                                      </section>

                                                                            {/* Why Choose GBTS */}
                                                                                  <section className="why-choose section-spacing">
                                                                                          <h2 className="section-title">Why Choose GBTS?</h2>
                                                                                                  <div className="feature-grid">
                                                                                                            <div className="feature-item">
                                                                                                                        <i className="fas fa-truck"></i>
                                                                                                                                    <h3>Fast Delivery</h3>
                                                                                                                                                <p>Nationwide delivery of all materials at unbeatable speed.</p>
                                                                                                                                                          </div>
                                                                                                                                                                    <div className="feature-item">
                                                                                                                                                                                <i className="fas fa-check-circle"></i>
                                                                                                                                                                                            <h3>Quality Assurance</h3>
                                                                                                                                                                                                        <p>We sell genuine and durable building products.</p>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                            <div className="feature-item">
                                                                                                                                                                                                                                        <i className="fas fa-headset"></i>
                                                                                                                                                                                                                                                    <h3>24/7 Support</h3>
                                                                                                                                                                                                                                                                <p>Our experts are always ready to help with your inquiries.</p>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                              {/* Product Categories */}
                                                                                                                                                                                                                                                                                                    <section className="featured-products section-spacing">
                                                                                                                                                                                                                                                                                                            <h2 className="section-title">Shop by Category</h2>
                                                                                                                                                                                                                                                                                                                    <div className="products-grid">
                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                        name: 'Roofings',
                                                                                                                                                                                                                                                                                                                                                                      link: '/roofings',
                                                                                                                                                                                                                                                                                                                                                                                    image: '<img src="/images/roofings.jpg" alt="Roofing" />
'
                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                          name: 'Hand Tools',
                                                                                                                                                                                                                                                                                                                                                                                                                                        link: '/hand-tools',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      image: '<img src="/images/hand-tools.jpg" alt="Hand Tools" />
'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Locks & Knobs',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          link: '/locks-Locks & Knobs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  image: '<img src="/images/locks-knobs.jpg" alt="Locks & Knobs" />
'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name: 'Security Cameras',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            link: '/security-cameras',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          image: '<img src="/images/security-cameras.jpg" alt="Security Cameras" />
'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: 'Appliances',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              link: '/appliances',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image: '<img src="/images/appliances.jpg" alt="Appliances" />'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ].map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="product-card" key={idx}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="product-image" style={{ backgroundImage: `url(${item.image})` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="product-overlay">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
